spring:
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:35432/cycling
    username: cycling
    password:
