version: '3.9'

volumes:
  postgres_cp_data:
    driver: local
  postgres_kc_data:
    driver: local
  pgadmin:
    driver: local

services:
  postgres_cp:
    image: postgres:14
    volumes:
      - postgres_cp_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cycling
      POSTGRES_USER: cycling
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "35432:5432"
    networks:
      - backend
  postgres_kc:
    image: postgres:13.4
    volumes:
      - postgres_kc_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "25432:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend

    ports:
      - "${PGADMIN_PORT:-5050}:80"
  keycloak:
    image: quay.io/keycloak/keycloak
    env_file:
      - ./keycloak.dev.env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_kc
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - "8081:8080"
    depends_on:
      - postgres_cp
      - postgres_kc
    networks:
      - backend
    command:
      - start-dev
networks:
  backend:
    name: backend
    driver: bridge