version: '3'

volumes:
  postgres_cp_data:
    driver: local
  postgres_kc_data:
    driver: local

services:
  postgres_cp:
    image: postgres:14
    volumes:
      - postgres_cp_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cycling
      POSTGRES_USER: cycling
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 35432:5432
  postgres_kc:
    image: postgres:13.4
    volumes:
      - postgres_kc_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 25432:5432
  keycloak:
    image: bitnami/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8180:8180
    depends_on:
      - postgres_cp
      - postgres_kc
